services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-picpay
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: picpay
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - postgres_data:/bitnami/postgresql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-picpay
    environment:
      PGADMIN_DEFAULT_EMAIL: desafio@admin.com
      PGADMIN_DEFAULT_PASSWORD: desafio
    ports:
      - "5050:80"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data: